[package]
name = "api"
version = "0.1.0"
authors = ["LeoRiether <leonardoalves8217@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1"
now_lambda = "*"
